package windmode;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import parserthing.Parser;
import parserthing.PredicateParseException;
import s2a.predicates.api.PredicateCreateException;

public class InterfaceFrame extends javax.swing.JFrame {
    
    String filename = "";
    
    private boolean rullesAdded = false;
    private boolean allRules = false;
    private boolean compRules = false;
    private boolean zeroRules = false;
    private boolean arithRules = false;
    private boolean ptrRules = false;
    private boolean addMannual = false;
    private List<String> addManNms = new ArrayList<String>() {};
    
    public InterfaceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addMan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addallCheckBox1 = new javax.swing.JCheckBox();
        addcompCheckBox2 = new javax.swing.JCheckBox();
        addzeroCheckBox3 = new javax.swing.JCheckBox();
        addarithCheckBox4 = new javax.swing.JCheckBox();
        addptrCheckBox5 = new javax.swing.JCheckBox();
        SavePrefsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        loadButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        proveButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        proveMenuItem = new javax.swing.JMenuItem();
        rulesMenuItem1 = new javax.swing.JMenuItem();

        jDialog1.setTitle("Preferences");
        jDialog1.setMinimumSize(new java.awt.Dimension(370, 287));
        jDialog1.setModal(true);
        jDialog1.setPreferredSize(new java.awt.Dimension(270, 200));
        jDialog1.setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Add all rules from library");

        jLabel2.setText("Add zero&nonzero rules");

        jLabel3.setText("Add comparison rules");

        jLabel4.setText("Add arithmetic rules");

        jLabel5.setText("Add pointer rules");

        addMan.setText("Add..");
        addMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManActionPerformed(evt);
            }
        });

        jLabel6.setText("Add rules from file");

        addallCheckBox1.setText("Add all");
        addallCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addallCheckBox1ActionPerformed(evt);
            }
        });

        addcompCheckBox2.setText(" Add comparison");

        addzeroCheckBox3.setText("Add zero&nonzero rules");

        addarithCheckBox4.setText("Add arithmetic rules");

        addptrCheckBox5.setText("Add pointer rules");

        SavePrefsBtn.setText("Save");
        SavePrefsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePrefsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addMan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addarithCheckBox4)
                            .addComponent(addzeroCheckBox3)
                            .addComponent(addcompCheckBox2)
                            .addComponent(addallCheckBox1)
                            .addComponent(addptrCheckBox5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(SavePrefsBtn)
                        .addGap(108, 108, 108))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addallCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addcompCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addzeroCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addarithCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addptrCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMan)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(SavePrefsBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textarea.setColumns(20);
        textarea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        proveButton.setText("Prove");
        proveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        LoadMenuItem.setText("Load");
        LoadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(LoadMenuItem);

        SaveMenuItem.setText("Save");
        SaveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SaveMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Logic");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        proveMenuItem.setText("Prove");
        proveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(proveMenuItem);

        rulesMenuItem1.setText("Rules...");
        rulesMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(rulesMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proveButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 116, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearButton))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            filename = file.getAbsolutePath();
            try {
              // What to do with the file, e.g. display it in a TextArea
              textarea.read( new FileReader( file.getAbsolutePath() ), null );
            } catch (IOException ex) {
              System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
        
    }//GEN-LAST:event_loadButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        filename = "";
        textarea.setText("");
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void proveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveButtonActionPerformed
        boolean result = false;
        if (textarea.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "The input data is empty", "ERROR!", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        Parser p = new Parser();
        try {
            if (allRules)
                p.addAllRules();  
            else {
                if (compRules)
                    p.addRules("rules/_Comparison.txt");  
                if (arithRules)
                    p.addRules("rules/_Arithmetic.txt");
                if (zeroRules)
                    p.addRules("rules/_ZeroNonzero.txt");
            }
        } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage() , "FAULT!", JOptionPane.DEFAULT_OPTION);
                return;
        }
        if (addMannual) {
            for (String f:addManNms)
                try {
                    p.addRules(f);
                } catch (IOException exe) {
                    JOptionPane.showMessageDialog(this, exe.getMessage() , "FAULT!", JOptionPane.DEFAULT_OPTION);
                    addManNms.remove(f);
                    return;
                }
            }
            
        try {
            result = p.prove_win(textarea.getText());
        } catch (IOException | PredicateParseException | PredicateCreateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() , "FAULT!", JOptionPane.DEFAULT_OPTION);
            return;
        }
        JOptionPane.showMessageDialog(this, "The result is " + result , "SUCCESS!", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_proveButtonActionPerformed

    private void LoadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadMenuItemActionPerformed
        loadButtonActionPerformed(evt);
    }//GEN-LAST:event_LoadMenuItemActionPerformed
    private void SaveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuItemActionPerformed
        JFileChooser chooser = new JFileChooser();
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(chooser.getSelectedFile().getAbsolutePath()));
                PrintWriter pw = new PrintWriter(chooser.getSelectedFile().getAbsolutePath());
                FileWriter fw = new FileWriter(chooser.getSelectedFile().getAbsolutePath());
                String[] parts = textarea.getText().split("\n");
                for (String s: parts)
                    bw.write(s);
                bw.flush();
                bw.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage() , "FAULT!", JOptionPane.DEFAULT_OPTION);

            }
            
        }
    }//GEN-LAST:event_SaveMenuItemActionPerformed

    private void proveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveMenuItemActionPerformed
        proveButtonActionPerformed(evt);
    }//GEN-LAST:event_proveMenuItemActionPerformed

    private void rulesMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesMenuItem1ActionPerformed
        jDialog1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_rulesMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void addallCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addallCheckBox1ActionPerformed
        if (addallCheckBox1.isSelected()) {
            addarithCheckBox4.setSelected(true);// TODO add your handling code here:
            addcompCheckBox2.setSelected(true);
            addzeroCheckBox3.setSelected(true);
            addptrCheckBox5.setSelected(true);
        }
        else {
            addarithCheckBox4.setSelected(false);// TODO add your handling code here:
            addcompCheckBox2.setSelected(false);
            addzeroCheckBox3.setSelected(false);
            addptrCheckBox5.setSelected(false);
        }
    }//GEN-LAST:event_addallCheckBox1ActionPerformed

    private void SavePrefsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePrefsBtnActionPerformed
        allRules = addallCheckBox1.isSelected();
        arithRules = addarithCheckBox4.isSelected();
        compRules = addcompCheckBox2.isSelected();
        zeroRules = addzeroCheckBox3.isSelected();
        ptrRules = addptrCheckBox5.isSelected();
        
        jDialog1.setVisible(false);
    }//GEN-LAST:event_SavePrefsBtnActionPerformed

    private void addManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            filename = file.getAbsolutePath();
            if (!addManNms.contains(filename))
            addManNms.add(filename);
            addMannual = true;
        }
    }//GEN-LAST:event_addManActionPerformed

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InterfaceFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfaceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoadMenuItem;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JButton SavePrefsBtn;
    private javax.swing.JButton addMan;
    private javax.swing.JCheckBox addallCheckBox1;
    private javax.swing.JCheckBox addarithCheckBox4;
    private javax.swing.JCheckBox addcompCheckBox2;
    private javax.swing.JCheckBox addptrCheckBox5;
    private javax.swing.JCheckBox addzeroCheckBox3;
    private javax.swing.JButton clearButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton proveButton;
    private javax.swing.JMenuItem proveMenuItem;
    private javax.swing.JMenuItem rulesMenuItem1;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
